title: F1 Risks
author: TomCOttin
email: ctom.99@outlook.fr
description: > # this means to ignore newlines until "baseurl:"
  This blog aims to aware people on how much mecanic sport F1 is dangerous for drivers' life.
theme : minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
